// Material Identity pass — a small procedural texture atlas so blocks carry
// real per-face material identity (not just a flat vertex color). Every pixel
// is generated by pure, seeded math (no Math.random, no Canvas2D/OffscreenCanvas
// — the test environment is jsdom, which has no real canvas backend, so a raw
// pixel buffer keeps this deterministic and unit-testable). The atlas is
// body-independent: biome color stays a separate per-body tint applied in the
// vertex palette (see voxelBiomes.ts) and diluted onto this texture in
// greedyMesh.ts/voxelMaterial.ts, never replacing it.
//
// getBlockFaceTileIndex is a pure, worker-safe lookup — greedyMesh.ts (which
// also runs inside mesher.worker.ts) calls it directly. getMaterialAtlasTexture
// builds the actual GPU texture lazily, so nothing DOM/WebGPU-related runs at
// module load, only when the main-thread material actually requests it.

import { DataTexture, RGBAFormat, NearestFilter } from 'three';
import { BLOCK, isOre, type BlockId } from './voxelTypes';
import { valueNoise2 } from './noise';

export const ATLAS_TILE_PX = 16;
export const ATLAS_GRID = 8;
export const ATLAS_PX = ATLAS_TILE_PX * ATLAS_GRID;
const ATLAS_SEED = 0xa17a5;

export type MaterialTile =
  | 'grass_top'
  | 'grass_side'
  | 'dirt'
  | 'stone'
  | 'sand'
  | 'ice'
  | 'ice_glow'
  | 'lava'
  | 'sulphur'
  | 'bark_side'
  | 'bark_top'
  | 'leaves'
  | 'metal'
  | 'panel'
  | 'glass'
  | 'ore_fleck'
  | 'build';

const TILE_INDEX: Record<MaterialTile, number> = {
  grass_top: 0,
  grass_side: 1,
  dirt: 2,
  stone: 3,
  sand: 4,
  ice: 5,
  ice_glow: 6,
  lava: 7,
  sulphur: 8,
  bark_side: 9,
  bark_top: 10,
  leaves: 11,
  metal: 12,
  panel: 13,
  glass: 14,
  ore_fleck: 15,
  build: 16,
};

type Pattern = 'fleck' | 'crack' | 'stripe' | 'leafmask' | 'flat';

interface TileStyle {
  base: [number, number, number];
  variation: [number, number, number];
  noiseFreq: number;
  pattern: Pattern;
}

const TILE_STYLE: Record<MaterialTile, TileStyle> = {
  grass_top: { base: [0.25, 0.55, 0.18], variation: [0.05, 0.08, 0.05], noiseFreq: 0.35, pattern: 'fleck' },
  // Bottom two-thirds of this tile reads as dirt (see paintTile's special case
  // below) — "grass = dirt-blended sides" per the material composition rule.
  grass_side: { base: [0.25, 0.55, 0.18], variation: [0.04, 0.05, 0.03], noiseFreq: 0.3, pattern: 'fleck' },
  dirt: { base: [0.36, 0.26, 0.16], variation: [0.05, 0.04, 0.03], noiseFreq: 0.4, pattern: 'fleck' },
  stone: { base: [0.5, 0.5, 0.52], variation: [0.1, 0.1, 0.1], noiseFreq: 0.55, pattern: 'crack' },
  sand: { base: [0.76, 0.68, 0.46], variation: [0.05, 0.04, 0.03], noiseFreq: 0.5, pattern: 'fleck' },
  ice: { base: [0.75, 0.85, 0.92], variation: [0.05, 0.05, 0.04], noiseFreq: 0.4, pattern: 'crack' },
  ice_glow: { base: [0.55, 0.75, 0.95], variation: [0.06, 0.07, 0.06], noiseFreq: 0.4, pattern: 'crack' },
  lava: { base: [0.95, 0.35, 0.05], variation: [0.12, 0.09, 0.04], noiseFreq: 0.5, pattern: 'fleck' },
  sulphur: { base: [0.82, 0.7, 0.15], variation: [0.06, 0.05, 0.03], noiseFreq: 0.45, pattern: 'fleck' },
  bark_side: { base: [0.32, 0.22, 0.14], variation: [0.05, 0.04, 0.03], noiseFreq: 0.35, pattern: 'stripe' },
  bark_top: { base: [0.38, 0.27, 0.17], variation: [0.05, 0.04, 0.03], noiseFreq: 0.5, pattern: 'crack' },
  leaves: { base: [0.16, 0.42, 0.14], variation: [0.08, 0.1, 0.06], noiseFreq: 0.55, pattern: 'leafmask' },
  metal: { base: [0.5, 0.52, 0.55], variation: [0.06, 0.06, 0.06], noiseFreq: 0.5, pattern: 'fleck' },
  panel: { base: [0.34, 0.36, 0.4], variation: [0.03, 0.03, 0.03], noiseFreq: 0.28, pattern: 'stripe' },
  glass: { base: [0.55, 0.7, 0.78], variation: [0.02, 0.02, 0.02], noiseFreq: 0.3, pattern: 'flat' },
  ore_fleck: { base: [0.4, 0.4, 0.42], variation: [0.12, 0.12, 0.12], noiseFreq: 0.6, pattern: 'fleck' },
  build: { base: [0.6, 0.62, 0.66], variation: [0.04, 0.04, 0.04], noiseFreq: 0.3, pattern: 'stripe' },
};

/** Deterministic per-pixel signed pattern value in [-1, 1] for a tile's
 *  local pixel coordinates. `tileSeed` decorrelates identical patterns
 *  across different tiles that happen to share a Pattern kind. */
function patternValue(lx: number, ly: number, tileSeed: number, freq: number, pattern: Pattern): number {
  switch (pattern) {
    case 'crack': {
      const n = valueNoise2(lx * freq, ly * freq, tileSeed);
      return n < 0.18 ? -1 : Math.min(1, (n - 0.18) / 0.5);
    }
    case 'stripe': {
      const n = valueNoise2(lx * freq * 0.4, ly * freq, tileSeed) * 2 - 1;
      const stripe = Math.sin(lx * 0.9) * 0.5;
      return Math.max(-1, Math.min(1, n * 0.6 + stripe));
    }
    case 'leafmask': {
      const n = valueNoise2(lx * freq, ly * freq, tileSeed) * 2 - 1;
      const clump = valueNoise2(lx * freq * 0.35, ly * freq * 0.35, tileSeed + 500) * 2 - 1;
      return Math.max(-1, Math.min(1, n * 0.6 + clump * 0.4));
    }
    case 'flat':
      return 0;
    case 'fleck':
    default:
      return valueNoise2(lx * freq, ly * freq, tileSeed) * 2 - 1;
  }
}

function clamp255(v: number): number {
  return Math.max(0, Math.min(255, Math.round(v)));
}

/** Paints one tile's pixels into `data` (RGBA, ATLAS_PX x ATLAS_PX). */
function paintTile(data: Uint8ClampedArray<ArrayBuffer>, tile: MaterialTile, idx: number): void {
  const style = TILE_STYLE[tile];
  const dirt = TILE_STYLE.dirt;
  const tileSeed = ATLAS_SEED + idx * 977;
  const ox = (idx % ATLAS_GRID) * ATLAS_TILE_PX;
  const oy = Math.floor(idx / ATLAS_GRID) * ATLAS_TILE_PX;

  for (let ly = 0; ly < ATLAS_TILE_PX; ly++) {
    // grass_side: top third reads as grass, the rest blends into dirt — the
    // "dirt-blended sides" terrain composition rule, baked as authored color
    // rather than left to a runtime tint.
    const grassT = tile === 'grass_side' ? Math.max(0, Math.min(1, (ly - 3) / 5)) : 0;
    for (let lx = 0; lx < ATLAS_TILE_PX; lx++) {
      const v = patternValue(lx, ly, tileSeed, style.noiseFreq, style.pattern);
      let r = style.base[0] + style.variation[0] * v;
      let g = style.base[1] + style.variation[1] * v;
      let b = style.base[2] + style.variation[2] * v;
      if (tile === 'grass_side') {
        const dv = patternValue(lx, ly, tileSeed + 1, dirt.noiseFreq, dirt.pattern);
        const dr = dirt.base[0] + dirt.variation[0] * dv;
        const dg = dirt.base[1] + dirt.variation[1] * dv;
        const db = dirt.base[2] + dirt.variation[2] * dv;
        r = r * (1 - grassT) + dr * grassT;
        g = g * (1 - grassT) + dg * grassT;
        b = b * (1 - grassT) + db * grassT;
      }
      const px = ox + lx;
      const py = oy + ly;
      const o = (py * ATLAS_PX + px) * 4;
      data[o] = clamp255(r * 255);
      data[o + 1] = clamp255(g * 255);
      data[o + 2] = clamp255(b * 255);
      data[o + 3] = 255;
    }
  }
}

let cachedPixels: Uint8ClampedArray<ArrayBuffer> | null = null;

/** Builds (once) the full atlas pixel buffer. Pure/deterministic, no DOM. */
function getAtlasPixels(): Uint8ClampedArray<ArrayBuffer> {
  if (cachedPixels) return cachedPixels;
  const data = new Uint8ClampedArray(ATLAS_PX * ATLAS_PX * 4);
  for (const tile of Object.keys(TILE_INDEX) as MaterialTile[]) {
    paintTile(data, tile, TILE_INDEX[tile]);
  }
  cachedPixels = data;
  return data;
}

let cachedTexture: DataTexture | null = null;

/** The GPU-side atlas texture — built and memoized lazily on first use (never
 *  at module load), so importing this module has zero DOM/WebGPU side effects
 *  and stays safe inside mesher.worker.ts. Body-independent: material
 *  identity is universal, only the per-body palette tint varies. */
export function getMaterialAtlasTexture(): DataTexture {
  if (cachedTexture) return cachedTexture;
  const tex = new DataTexture(getAtlasPixels(), ATLAS_PX, ATLAS_PX, RGBAFormat);
  tex.magFilter = NearestFilter;
  tex.minFilter = NearestFilter;
  tex.needsUpdate = true;
  cachedTexture = tex;
  return tex;
}

function uniform(t: MaterialTile): { top: MaterialTile; side: MaterialTile; bottom: MaterialTile } {
  return { top: t, side: t, bottom: t };
}

/** Per-block-id face material mapping. Most blocks use one tile on every
 *  face; grass and wood distinguish top/side/bottom (the "geometry + texture
 *  must contribute, not just color" requirement). */
export function getBlockFaceTiles(id: BlockId): { top: MaterialTile; side: MaterialTile; bottom: MaterialTile } {
  switch (id) {
    case BLOCK.GRASS:
      return { top: 'grass_top', side: 'grass_side', bottom: 'dirt' };
    case BLOCK.SURFACE:
    case BLOCK.SUBSOIL:
      return uniform('dirt');
    case BLOCK.ROCK:
      return uniform('stone');
    case BLOCK.SAND:
      return uniform('sand');
    case BLOCK.ICE:
      return uniform('ice');
    case BLOCK.ICE_GLOW:
      return uniform('ice_glow');
    case BLOCK.LAVA:
      return uniform('lava');
    case BLOCK.SULPHUR:
      return uniform('sulphur');
    case BLOCK.METAL:
      return uniform('metal');
    case BLOCK.PANEL:
      return uniform('panel');
    case BLOCK.GLASS:
      return uniform('glass');
    case BLOCK.WOOD_LOG:
      return { top: 'bark_top', side: 'bark_side', bottom: 'bark_top' };
    case BLOCK.LEAVES:
      return uniform('leaves');
    case BLOCK.BUILD:
    case BLOCK.SILO:
    case BLOCK.STATION:
    case BLOCK.HABITAT:
    case BLOCK.SOLAR:
    case BLOCK.WIND:
    case BLOCK.THERMAL:
    case BLOCK.REFINERY:
    case BLOCK.TETHER:
    case BLOCK.EXTRACTOR:
    case BLOCK.CONDENSER:
      return uniform('build');
    default:
      return uniform(isOre(id) ? 'ore_fleck' : 'build');
  }
}

/** Worker-safe pure lookup: which atlas tile a given voxel face (sweep axis
 *  `axis` 0/1/2, face direction `dir` +1/-1) should sample. `axis === 1` is
 *  the vertical (y) sweep — dir>0 is the top face, dir<0 the bottom face;
 *  axis 0/2 (x/z sweeps) are always side faces regardless of dir. */
export function getBlockFaceTileIndex(id: BlockId, axis: number, dir: number): number {
  const tiles = getBlockFaceTiles(id);
  const role = axis === 1 ? (dir > 0 ? 'top' : 'bottom') : 'side';
  return TILE_INDEX[tiles[role]];
}

/** Tile origin in 0..1 atlas UV space. */
export function tileUVRect(idx: number): [number, number] {
  return [(idx % ATLAS_GRID) / ATLAS_GRID, Math.floor(idx / ATLAS_GRID) / ATLAS_GRID];
}
